README.md
XIPs/xip-0-purpose-process.md
XIPs/xip-5-message-content-types.md
XIPs/xip-9-composite-content-type.md
XIPs/xip-composite-content-type.md

Based on XIP-5 this XRC proposes a new content type `xtmp.org/composite:1.0` for multi-part messages where the parts can be of any content type and the composite parts can be arbitrarily nested.
Reference implementation https://github.com/xmtp/xmtp-js/pull/96

XRC-9: Composite content type

---

XIPs/xip-0-purpose-process.md

- Proposes that we change relative links to full URLs in `xip-0-purpose-process.md` so that we can single-source this great content to the `xmtp-dot-org` repo and publish it to the Dev Portal. (Relative links break in the context of the `xmtp-dot-org` repo.)
- Updates "Standards Track" to "Standards" per a change in terms we used in the XMTP Litepaper
- Updates community forum URLs to point to the XMTP GitHub Discussions - XIPs category
- Updates title value in page header to use sentence case and "and" instead of "&" to match documentation style
- Makes a few nit edits

Edits to links to enable single-sourcing of xip-0-purpose-process.md

---

XIPs/xip-5-message-content-types.md

Based on developers building custom content types that use `xmtp.org` as the `authorityId`, we thought it might be good to update XIP-5's definition of the authority ID to state that the `xmtp.org` `authorityId` value is reserved for standard content types.

Clarify that xmtp.org is a reserved authorityId value

---

XIPs/xip-17-remote-attachment-content-type-proposal.md

A suggestion for how we can handle larger messages but maintain E2E encryption.

Remote Attachment Content Type Proposal

---

XIPs/xip-reaction-content-type.md

Draft for XIP reaction content type, following up on idea here: https://community.xmtp.org/t/proposal-for-emoji-reactions-content-type/499/2

xip-reaction-content-type.md

---

XIPs/xip-37-universal-allow-block-preferences.md
XIPs/xip-42-universal-allow-block-preferences.md

Discussion to <https://community.xmtp.org/t/xip-37-universal-allow-and-block-preferences/544>

XIP-42: Universal 'allow' and 'block' preferences

---

XIPs/xip-21-transaction-reference-content-type.md

https://community.xmtp.org/t/xip-21-on-chain-transaction-reference-content-type/532/2?u=jha

XIP-21: Incorporate suggestion from Aurel/Chain Agnostic Initiative

---

XIPs/xip-21-transaction-reference-content-type.md

Moving XIP to Last Call status after incorporating feedback from community.
After 14 days in Last Call status with no normative changes, XIP will move into Final status.

Update XIP-21 to Last call status

---

XIPs/xip-36-frames-support.md

Ready for Review status.
Left a few comments for review by @neekolas and @daria-github - thank you!

XIP-36: Frames Support in Review status

---

XIPs/xip-47-group-chat-permissions.md

Any suggestions on formatting updates would be appreciated, thanks!

Added threat model section to XIP 47

---

XIPs/xip-48-content-type-local-db-integration.md

Queryable Content Types in Rust

---

XIPs/xip-49-decentralized-backend.md

This PR removes the responsibility of the client to determine a node to send the message to.
Instead, it becomes the payer's decision how to route messages in the system.
Remove the load balancing code and recommend stable hashing (ring hashing) instead.

Pull originator ID from AAD in XIP-49

---

XIPs/xip-57-content-type-wallet-send-calls.md
XIPs/xip-59-content-type-wallet-send-calls.md

Author: @justjkk 
This content type provides a standard format for triggering on-chain calls typically by a programmatic agent like an AI agent responding to a user request.
Demo application can be accessed at: https://xmtp.heyelsa.ai/dm/0xE15AA1ba585AeA8a4639331ce5f9aEc86f8c4541
Reference implementation for the content-type: https://github.com/HeyElsa/xmtp-js/tree/main/content-types/content-type-wallet-send-calls

Content Type for initiating transactions by DeFAI agent

---

XIPs/xip-65-typing-notifications.md

Introduces a new XIP specification document [xip-65-typing-notifications.md](https://github.com/xmtp/XIPs/pull/108/files#diff-4736e078e7f1bea6036c2a745d9746ec39fb8206f6a975d0ccf5bb716a299b21) that outlines the technical implementation for typing indicators in XMTP, including:
* Implementation of ephemeral messages using a new `sendOption` flag
* Creation of dedicated ephemeral topics for typing notification streams
* Specification of message streaming methods for typing indicators
* Documentation of backward compatibility considerations and security implications
Begin by reviewing the specification document at [xip-65-typing-notifications.md](https://github.com/xmtp/XIPs/pull/108/files#diff-4736e078e7f1bea6036c2a745d9746ec39fb8206f6a975d0ccf5bb716a299b21), which contains the complete …

XIP-65: Typing notifications

---

XIPs/xip-61-edit-and-delete-mesages.md
xip-61-edit-and-delete-mesages.md

Added new specification document defining message editing and deletion functionality for XMTP, including `UpdateMessage` content type, API methods, and security considerations

Add XIP-61: Edit and delete messages

---

.github/workflows/stale.yml

Adds a new GitHub Actions workflow that manages pull request lifecycle through the `actions/stale@v9` action. The workflow:
* Marks PRs as stale after 182 days of inactivity and adds a `stale` label
* Closes stale PRs after an additional 7 days without activity
* Excludes PRs with `keep-open` label from being marked as stale
* Runs on a daily schedule at midnight
* Configured in [stale.yml](https://github.com/xmtp/XIPs/pull/109/files#diff-b5e0854ed0838024d5cc25b4e030922e34648b9ea8c432807e35495fb805b894)
Review the workflow configuration in [stale.yml](https://github.com/xmtp/XIPs/pull/109/files#diff-b5e0854ed0838024d5cc25b4e030922e34648b9ea8c432807e35495fb805b894) which contains all the settings for the stale PR automation.
----
_[Macroscope](https://app.macroscope.com) summarized …

Add stalebot to help moderate stale PRs

---

XIPs/xip-53-v2-deprecation.md

This change updates the deprecation schedule in [XIPs/xip-53-v2-deprecation.md](https://github.com/xmtp/XIPs/pull/111/files#diff-2c0e44cb2642dfd8d7c1ee29a5eece57af80d6d5c15bab07ea412738575e2d5e) by extending the timeline by approximately 7 weeks. The read-only transition period start date moves from April 1, 2025 to May 1, 2025, the Tuesday and Thursday read-only periods shift from April 2025 dates to May 2025 dates (1, 6, 8, 13, 15, 20, 22, 27, and 29), and the permanent read-only mode date changes from May 1, 2025 to June 23, 2025.
Start with the timeline section in [XIPs/xip-53-v2-deprecation.md](https://github.com/xmtp/XIPs/pull/111/files#diff-2c0e44cb2642dfd8d7c1ee29a5eece57af80d6d5c15bab07ea412738575e2d5e) where the deprecation dates are specified.
---- …

Update v2 read-only date in XIP-53: XMTP V2 deprecation

---

XIPs/xip-x-local-db-mgmt.md

Adds a new XIP (XMTP Improvement Proposal) document [XIPs/xip-x-local-db-mgmt.md](https://github.com/xmtp/XIPs/pull/114/files#diff-fbbe250f6f22e0de6de7f26e5fa7d7e7ac761775340b6908520a43dca5a2a0fd) that proposes database management functions for local SQLite databases. The proposal defines six new methods: `Client.findLocalDatabase` for checking encrypted database existence, `client.deleteLocalDatabase` for removing local databases, `conversation.deleteMessages` for deleting messages by date and content type, `conversations.deleteMessages` for bulk message deletion by consent state, `conversation.deleteMessage` for single message removal, and `conversations.addLocalMessage` for adding messages locally without network transmission.
Start with the specification section in …

XIP-70: Local database management tools

---

XIPs/xip-71-archive-based-backups.md

Introduces a new XMTP Improvement Proposal document that specifies archive-based backup functionality for XMTP conversations, messages, and consent data. The specification defines three core methods (`createArchive`, `archiveMetadata`, and `importArchive`) for creating encrypted SQLite-based archives and importing them into new installations, with imported conversations starting in an inactive, read-only state until proper MLS integration occurs.
Start with the new specification document [XIPs/xip-71-archive-based-backups.md](https://github.com/xmtp/XIPs/pull/115/files#diff-0ded09309691400c2452d226915b068380861c84334c266fc9b8379089dd7707) to understand the proposed archive-based backup functionality and API methods.
----
_[Macroscope](https://app.macroscope.com) summarized 8d30e3b._

XIP-71: Archive-based backups

---

XIPs/xip-50-multiple-remote-attachments-content-type.md

This change updates the XIP front-matter to reflect its finalization and includes a link to the implementation documentation.
- Change `status` from `Review` to `Final` in [xip-50-multiple-remote-attachments-content-type.md](https://github.com/xmtp/XIPs/pull/124/files#diff-08bb670a0662464c9bc127e2edd4292f02b7ecaf99b1b17b1df4de118cb1ed21)
- Add `implementation` field with a URL to documentation for supporting multiple remote attachments of any size in [xip-50-multiple-remote-attachments-content-type.md](https://github.com/xmtp/XIPs/pull/124/files#diff-08bb670a0662464c9bc127e2edd4292f02b7ecaf99b1b17b1df4de118cb1ed21)
Start with the front-matter in [XIPs/xip-50-multiple-remote-attachments-content-type.md](https://github.com/xmtp/XIPs/pull/124/files#diff-08bb670a0662464c9bc127e2edd4292f02b7eca …

XIP-50 to final, add impl link

---

XIPs/xip-47-group-chat-permissions.md

Update the XIP front-matter in [XIPs/xip-47-group-chat-permissions.md](https://github.com/xmtp/XIPs/pull/126/files#diff-5e8935d37662ce15567f04a6be5c76abaadc7657b81363cb9825f305b403609a) by changing `status` from `Review` to `Final` and adding an `implementation` URL field pointing to the docs.
Start with the front-matter changes at the top of [XIPs/xip-47-group-chat-permissions.md](https://github.com/xmtp/XIPs/pull/126/files#diff-5e8935d37662ce15567f04a6be5c76abaadc7657b81363cb9825f305b403609a).
----
_[Macroscope](https://app.macroscope.com) summarized 835f764._

XIP-47 to final status

---

XIPs/xip-15-attachment-content-type.md

This change updates the front-matter of the XIP-15 document.
- Set `status` to `Final` in [XIPs/xip-15-attachment-content-type.md](https://github.com/xmtp/XIPs/pull/127/files#diff-8c46b35da8bbf8790d6952d28008179493a269f31de12abdf59e6a980225df09)
- Set `type` to `Standards` in [XIPs/xip-15-attachment-content-type.md](https://github.com/xmtp/XIPs/pull/127/files#diff-8c46b35da8bbf8790d6952d28008179493a269f31de12abdf59e6a980225df09)
- Add `implementation` link to https://docs.xmtp.org/chat-apps/content-types/attachments#support-attachments-smaller-than-1mb in [XIPs/xip-15-attachment-content-type.md](https://github.com/xmtp/XIPs/pull/127/files#diff-8c46b35da8bbf8790d6952d28008179493a269f31de12abdf59e6a980225df09)
Start with the front-matter changes in …

XIP-15 to final, impl link
